# Site settings
title: Quantum Untangled
description: > # this means to ignore newlines until "baseurl:"
  An open-source community making quantum computing, physics, mathematics and all the related fields
  accessible to audiences from all levels of expertise.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://epelaaez.github.io/Quantum-Untangled" # the base hostname & protocol for your site

# Markdown settings
markdown: kramdown

# Sass settings
sass:
  add_charset: true
  sass_dir: assets/sass
  style: :compressed

# Build settings
exclude:
  - package.json
  - README.md
  - docs
  - CNAME
  - assets/sass
  - "bower_components"
  - "bower.json"
  - "node_modules"
  - "package.json"
  - "Gruntfile.coffee"
  - "Rakefile"

include:
  - .nojekyll

# Plugin settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
