# Generated by Django 3.1.7 on 2021-03-22 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210311_1411'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='name',
            new_name='db_name',
        ),
        migrations.AddField(
            model_name='tag',
            name='display_name',
            field=models.CharField(default='test', max_length=30),
            preserve_default=False,
        ),
    ]
