# Generated by Django 3.1.7 on 2021-04-01 20:48

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='posttagindexpage',
            name='intro',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
