# Generated by Django 3.1.7 on 2021-04-04 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_blogcategory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogCategory',
            new_name='PostCategory',
        ),
    ]
