# Generated by Django 3.1.7 on 2021-04-04 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20210403_2306'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postcategory',
            options={'verbose_name_plural': 'post categories'},
        ),
    ]
