# Generated by Django 3.1.7 on 2021-04-04 05:14

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20210403_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='postpage',
            name='categories',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='blog.PostCategory'),
        ),
    ]
